baseURL = 'https://accentdesign.github.io/gcss/'
languageCode = 'en-us'
title = 'gcss'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[params]
    custom_css = [
        'css/alerts.css',
        'css/badges.css',
        'css/buttons.css',
        'css/form.css',
        'css/tables.css'
    ]